
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eco_Colocation.Controllers
{

	using System;
	using System.Collections.Generic;

	public partial class Account
	{

		public Account()
		{

			this.Activated = true;

			this.RentalAd = new HashSet<RentalAd>();

			this.Role = new HashSet<Role>();

		}


		public int IdAccount { get; set; }

		public System.DateTime CreationDate { get; set; }

		public bool Activated { get; set; }



		public virtual ICollection<RentalAd> RentalAd { get; set; }

		public virtual User User { get; set; }

		public virtual Membership Membership { get; set; }

		public virtual ICollection<Role> Role { get; set; }

	}

}
