//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AnnonceLocation = new HashSet<AnnonceLocation>();
            this.Role = new HashSet<Role>();
        }
    
        public int IdAccount { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual ICollection<AnnonceLocation> AnnonceLocation { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Adhesion Adhesion { get; set; }
        public virtual ICollection<Role> Role { get; set; }
    }
}
