//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnonceProjetCreation
    {
        public AnnonceProjetCreation()
        {
            this.LieuProjetCreation = new HashSet<Lieu>();
            this.Image = new HashSet<Image>();
        }
    
        public int IdAnnonceProjetCreation { get; set; }
        public string Description { get; set; }
        public byte EngagementTerrain { get; set; }
        public int SuperficieMaxTerrain { get; set; }
        public byte EngagementLogement { get; set; }
        public byte TypeHabitat { get; set; }
        public byte ImplantationLogement { get; set; }
        public int SuperficieMaxLogement { get; set; }
        public int CoutAchatMaxLogement { get; set; }
        public int LoyerMaxLogement { get; set; }
        public int CoutConstructionLogement { get; set; }
        public bool AccesHandicape { get; set; }
        public int NbPersoTotal { get; set; }
        public int NbPersAchatTerrain { get; set; }
        public int NbPersLocationLogement { get; set; }
        public bool AccesTransportCommun { get; set; }
        public string InfoSupAccessibilite { get; set; }
        public bool ConsoAlcoolTolerence { get; set; }
        public bool FumeurTolerence { get; set; }
        public bool AnimauxTolerence { get; set; }
        public string InfoSupTolerence { get; set; }
        public string DescriptionPersonnalite { get; set; }
        public int IdUsers { get; set; }
    
        public virtual ICollection<Lieu> LieuProjetCreation { get; set; }
        public virtual webpages_Users webpages_Users { get; set; }
        public virtual ICollection<Image> Image { get; set; }
    }
}
