//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversationDev
    {
        public ConversationDev()
        {
            this.Image = new HashSet<ImageConversationDev>();
        }
    
        public int IdConversationDev { get; set; }
        public string Message { get; set; }
        public string DateDernierEnvoi { get; set; }
    
        public virtual ICollection<ImageConversationDev> Image { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
