
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eco_Colocation.Controllers
{
	using System.Collections.Generic;

	public partial class DevConversation
{

    public DevConversation()
    {

        this.Viewed = 0;

        this.PictureDevConversation = new HashSet<PictureDevConversation>();

    }


    public int IdDevConversation { get; set; }

    public string Email { get; set; }

    public string Message { get; set; }

    public System.DateTime DateLastSend { get; set; }

    public byte Viewed { get; set; }



    public virtual ICollection<PictureDevConversation> PictureDevConversation { get; set; }

}

}
