//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcoColocExistante
    {
        public EcoColocExistante()
        {
            this.Colocataire = new HashSet<Colocataire>();
            this.EcoColocImage = new HashSet<Image>();
        }
    
        public int IdEcoColocExistante { get; set; }
        public string NomEcoColoc { get; set; }
        public int NbColocataire { get; set; }
        public string Pays { get; set; }
        public string Region { get; set; }
        public string Departement { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public byte ImplicationEcologique { get; set; }
        public string TableauEcolo { get; set; }
        public string TableauHabitat { get; set; }
    
        public virtual ICollection<Colocataire> Colocataire { get; set; }
        public virtual ICollection<Image> EcoColocImage { get; set; }
        public virtual webpages_Users webpages_Users { get; set; }
    }
}
