//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoColocationModelContainer : DbContext
    {
        public EcoColocationModelContainer()
            : base("name=EcoColocationModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RentalAd> AnnonceLocation { get; set; }
        public DbSet<RentalRoom> ChambreLocation { get; set; }
        public DbSet<CreationProjectAd> ProjetCreation { get; set; }
        public DbSet<Place> Lieu { get; set; }
        public DbSet<Event> Evenement { get; set; }
        public DbSet<PresenceEvent> EvenementPresence { get; set; }
        public DbSet<EcoRoommateExisting> EcoColocExistante { get; set; }
        public DbSet<PictureDevConversation> ImageConversationDev { get; set; }
        public DbSet<PeopleEcoRoommateExisting> Colocataire { get; set; }
        public DbSet<DevConversation> ConversationDev { get; set; }
        public DbSet<ResearchRoommate> RechercheColocation { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<AssociatedEvent> EvenementAssocie { get; set; }
        public DbSet<Membership> Adhesion { get; set; }
        public DbSet<PictureEcoRoommateEx> ImageEcoColocEx { get; set; }
        public DbSet<PictureCreationProject> ImageProjetCreation { get; set; }
        public DbSet<Account> Account { get; set; }
        public DbSet<Agency> Agence { get; set; }
        public DbSet<User> Utilisateur { get; set; }
    }
}
