//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoColocationModelContainer : DbContext
    {
        public EcoColocationModelContainer()
            : base("name=EcoColocationModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnnonceLocation> AnnonceLocationSet { get; set; }
        public DbSet<ChambreLocation> ChambreLocationSet { get; set; }
        public DbSet<AnnonceProjetCreation> AnnonceProjetCreationSet { get; set; }
        public DbSet<Lieu> LieuSet { get; set; }
        public DbSet<Evenement> EvenementSet { get; set; }
        public DbSet<EvenementPresence> EvenementPresenceSet { get; set; }
        public DbSet<EvenementPublication> EvenementPublicationSet { get; set; }
        public DbSet<EcoColocExistante> EcoColocExistanteSet { get; set; }
        public DbSet<Image> ImageSet { get; set; }
        public DbSet<Colocataire> ColocataireSet { get; set; }
        public DbSet<ConversationDev> ConversationDevSet { get; set; }
        public DbSet<RechercheColocation> RechercheColocationSet { get; set; }
        public DbSet<webpages_Membership> webpages_MembershipSet { get; set; }
        public DbSet<webpages_Roles> webpages_RolesSet { get; set; }
        public DbSet<webpages_Users> webpages_UsersSet { get; set; }
        public DbSet<EvenementAssocie> EvenementAssocieSet { get; set; }
    }
}
