//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoColocationModelContainer : DbContext
    {
        public EcoColocationModelContainer()
            : base("name=EcoColocationModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RentalAd> RentalAd { get; set; }
        public DbSet<RentalRoom> RentalRoom { get; set; }
        public DbSet<CreationProjectAd> CreationProjectAd { get; set; }
        public DbSet<Place> Place { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<PresenceEvent> PresenceEvent { get; set; }
        public DbSet<EcoRoommateExisting> EcoRoommateExisting { get; set; }
        public DbSet<PictureDevConversation> PictureDevConversation { get; set; }
        public DbSet<Roommate> Roommate { get; set; }
        public DbSet<DevConversation> DevConversation { get; set; }
        public DbSet<ResearchRoommate> ResearchRoommate { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<AssociatedEvent> AssociatedEvent { get; set; }
        public DbSet<Membership> Membership { get; set; }
        public DbSet<PictureEcoRoommateEx> PictureEcoRoommateEx { get; set; }
        public DbSet<PictureCreationProject> PictureCreationProject { get; set; }
        public DbSet<Account> Account { get; set; }
        public DbSet<Agency> Agency { get; set; }
        public DbSet<User> User { get; set; }
    }
}
