//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcoRoommateExisting
    {
        public EcoRoommateExisting()
        {
            this.PictureEcoRoommateEx = new HashSet<PictureEcoRoommateEx>();
        }
    
        public int IdEcoRoommateExisting { get; set; }
        public int IdUser { get; set; }
        public string NomEcoColoc { get; set; }
        public short NbColocataire { get; set; }
        public string Pays { get; set; }
        public string Region { get; set; }
        public string Departement { get; set; }
        public string NumDepartement { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public byte ImplicationEcologique { get; set; }
        public string TableauEcolo { get; set; }
        public string TableauHabitat { get; set; }
    
        public virtual ICollection<PictureEcoRoommateEx> PictureEcoRoommateEx { get; set; }
        public virtual User User { get; set; }
    }
}
