//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvenementPresence
    {
        public int IdEvenementPresence { get; set; }
        public byte Statut { get; set; }
        public int IdUser { get; set; }
        public int IdEvenement { get; set; }
    
        public virtual webpages_Users webpages_Users { get; set; }
        public virtual Evenement Evenement { get; set; }
    }
}
