
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eco_Colocation.Controllers
{
	using System.Collections.Generic;

	public partial class Event
{

    public Event()
    {

        this.PresenceEvent = new HashSet<PresenceEvent>();

        this.AssociatedEvent = new HashSet<AssociatedEvent>();

        this.AssociatedEvent1 = new HashSet<AssociatedEvent>();

    }


    public int IdEvent { get; set; }

    public int IdUser { get; set; }

    public System.DateTime DateStart { get; set; }

    public System.DateTime DateEnd { get; set; }

    public string StreetNumber { get; set; }

    public string StreetName { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Department { get; set; }

    public string DepartmentNumber { get; set; }

    public string Region { get; set; }

    public string Country { get; set; }

    public string Link { get; set; }

    public string Description { get; set; }

    public string PictureName { get; set; }

    public System.DateTime DatePublish { get; set; }



    public virtual ICollection<PresenceEvent> PresenceEvent { get; set; }

    public virtual ICollection<AssociatedEvent> AssociatedEvent { get; set; }

    public virtual ICollection<AssociatedEvent> AssociatedEvent1 { get; set; }

    public virtual User User { get; set; }

}

}
