//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int IdEcoColocImage { get; set; }
        public int IdEcoColocExistante { get; set; }
        public int IdAnnonceProjetCreation { get; set; }
        public int IdConversationDev { get; set; }
        public string NomImage { get; set; }
        public byte Numero { get; set; }
    
        public virtual EcoColocExistante EcoColocExistante { get; set; }
        public virtual AnnonceProjetCreation AnnonceProjetCreation { get; set; }
        public virtual ConversationDev ConversationDev { get; set; }
    }
}
