//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieu
    {
        public Lieu()
        {
            this.AnnonceProjetCreation = new HashSet<AnnonceProjetCreation>();
            this.RechercheColocation = new HashSet<RechercheColocation>();
        }
    
        public int IdLieu { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string Departement { get; set; }
        public string Region { get; set; }
        public string Pays { get; set; }
    
        public virtual ICollection<AnnonceProjetCreation> AnnonceProjetCreation { get; set; }
        public virtual ICollection<RechercheColocation> RechercheColocation { get; set; }
    }
}
