
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eco_Colocation.Controllers
{

using System;
    using System.Collections.Generic;
    
public partial class Person
{

    public int IdPerson { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public byte Civility { get; set; }

    public string Country { get; set; }

    public System.DateTime DateBirth { get; set; }

    public byte Activity { get; set; }

    public string PhoneCode { get; set; }

    public string PhoneNumber { get; set; }

    public byte ContactType { get; set; }

    public string PersonnalityDescription { get; set; }

    public System.DateTime DateInscription { get; set; }

    public System.DateTime DateLastActivity { get; set; }

}

}
