//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.CreationProject = new HashSet<CreationProjectAd>();
            this.ResearchRoommate = new HashSet<ResearchRoommate>();
        }
    
        public int IdPlace { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string Departement { get; set; }
        public string NumDepartement { get; set; }
        public string Region { get; set; }
        public string Pays { get; set; }
    
        public virtual ICollection<CreationProjectAd> CreationProject { get; set; }
        public virtual ICollection<ResearchRoommate> ResearchRoommate { get; set; }
    }
}
