
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eco_Colocation.Controllers
{

using System;
    using System.Collections.Generic;
    
public partial class Place
{

    public int IdPlace { get; set; }

    public Nullable<int> IdResearchRoommate { get; set; }

    public Nullable<int> IdCreationProject { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Department { get; set; }

    public string DepartmentNumber { get; set; }

    public string Region { get; set; }

    public string Country { get; set; }

    public byte ScopeResearch { get; set; }

}

}
