//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetCreation
    {
        public ProjetCreation()
        {
            this.Lieu = new HashSet<Lieu>();
            this.ImageProjetCreation = new HashSet<ImageProjetCreation>();
        }
    
        public int IdProjetCreation { get; set; }
        public int IdUtilisateur { get; set; }
        public string Introduction { get; set; }
        public string Description { get; set; }
        public Nullable<byte> EngagementTerrain { get; set; }
        public Nullable<int> SuperficieMaxTerrain { get; set; }
        public Nullable<int> CoutAchatMaxTerrain { get; set; }
        public byte EngagementLogement { get; set; }
        public byte TypeHabitat { get; set; }
        public byte ImplantationLogement { get; set; }
        public int SuperficieMaxLogement { get; set; }
        public Nullable<int> CoutAchatMaxLogement { get; set; }
        public Nullable<int> LoyerMaxLogement { get; set; }
        public Nullable<int> CoutConstructionMaxLogement { get; set; }
        public short NbPersoTotal { get; set; }
        public Nullable<short> NbPersAchatTerrain { get; set; }
        public Nullable<short> NbPersAchatLogement { get; set; }
        public Nullable<short> NbPersLocationLogement { get; set; }
        public byte AccesTransportCommun { get; set; }
        public string InfoSupAccessibilite { get; set; }
        public bool ConsoAlcoolTolerence { get; set; }
        public bool FumeurTolerence { get; set; }
        public bool AnimauxTolerence { get; set; }
        public string InfoSupTolerence { get; set; }
        public string ActivationAnnonce { get; set; }
    
        public virtual ICollection<Lieu> Lieu { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<ImageProjetCreation> ImageProjetCreation { get; set; }
    }
}
