
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eco_Colocation.Controllers
{

using System;
    using System.Collections.Generic;
    
public partial class RentalRoom
{

    public int IdRentalRoom { get; set; }

    public int IdRentalAd { get; set; }

    public decimal RentPrice { get; set; }

    public decimal Charges { get; set; }

    public string ChargesDetail { get; set; }

    public Nullable<decimal> Caution { get; set; }

    public short Surface { get; set; }

    public bool Furnished { get; set; }

    public System.DateTime AvalaibleDate { get; set; }

    public Nullable<System.DateTime> AvalaibleEndDate { get; set; }

}

}
