//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Utilisateur = new HashSet<Utilisateur>();
        }
    
        public int IdRole { get; set; }
        public string NomRole { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Utilisateur> Utilisateur { get; set; }
    }
}
