//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.Activation = true;
            this.Role = new HashSet<Role>();
            this.ProjetCreation = new HashSet<ProjetCreation>();
            this.AnnonceLocation = new HashSet<AnnonceLocation>();
            this.EvenementPresence = new HashSet<EvenementPresence>();
            this.Evenement = new HashSet<Evenement>();
        }
    
        public int IdUtilisateur { get; set; }
        public string Email { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public byte Civilite { get; set; }
        public string Pays { get; set; }
        public string DateNaissance { get; set; }
        public Nullable<byte> Activite { get; set; }
        public string Telephone { get; set; }
        public byte TypeContact { get; set; }
        public System.DateTime DateInscription { get; set; }
        public string DateDerniereActivite { get; set; }
        public bool Activation { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<ProjetCreation> ProjetCreation { get; set; }
        public virtual ICollection<AnnonceLocation> AnnonceLocation { get; set; }
        public virtual ICollection<EvenementPresence> EvenementPresence { get; set; }
        public virtual ICollection<Evenement> Evenement { get; set; }
    }
}
