//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.ActivationCompte = true;
            this.ProjetCreation = new HashSet<ProjetCreation>();
        }
    
        public int IdUtilisateur { get; set; }
        public string Email { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public byte Civilite { get; set; }
        public string Pays { get; set; }
        public string DateNaissance { get; set; }
        public Nullable<byte> Activite { get; set; }
        public string CodeTelPays { get; set; }
        public string Telephone { get; set; }
        public Nullable<byte> TypeContact { get; set; }
        public string DescriptionPersonnalite { get; set; }
        public System.DateTime DateInscription { get; set; }
        public System.DateTime DateDerniereActivite { get; set; }
        public bool ActivationCompte { get; set; }
    
        public virtual ICollection<ProjetCreation> ProjetCreation { get; set; }
    }
}
