//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eco_Colocation.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_Users
    {
        public webpages_Users()
        {
            this.Activited = true;
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.webpages_Membership = new HashSet<webpages_Membership>();
            this.AnnonceProjetCreation = new HashSet<AnnonceProjetCreation>();
            this.AnnonceLocation = new HashSet<AnnonceLocation>();
            this.EvenementPresence = new HashSet<EvenementPresence>();
        }
    
        public int UsersId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte Civilite { get; set; }
        public string Pays { get; set; }
        public string DateNaissance { get; set; }
        public Nullable<byte> Activites { get; set; }
        public string Telephone { get; set; }
        public byte TypeContact { get; set; }
        public System.DateTime DateInscription { get; set; }
        public bool Activited { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<webpages_Membership> webpages_Membership { get; set; }
        public virtual ICollection<AnnonceProjetCreation> AnnonceProjetCreation { get; set; }
        public virtual ICollection<AnnonceLocation> AnnonceLocation { get; set; }
        public virtual ICollection<EvenementPresence> EvenementPresence { get; set; }
    }
}
